### ISSUE TITLE
i have a probleme when running setup.sh

### ISSUE THREAD

**Issue by aymen-souid** [juntaoy/aracoref#2]
thank you for your amazing work, coreference resolution task for Arabic language is really underrated and I'm really impressed by the results 
So I tried to execute your code but I got this error when executing setup.sh
could you help me?
[](url)
![error](https://user-images.githubusercontent.com/92583830/141156904-70000e53-1b14-4380-9ca2-ef215cf4d67e.png)

**Comment by juntaoy** [comment]
Hi, I am not sure the reason for this error. I compiled this in both macOS and Linux, I didn't get any errors.  it might be the TensorFlow versions did you install the 1.7 version of TensorFlow as shown in the requirement.txt?

**Comment by aymen-souid** [comment]
yes ,it was resolved thank you

**Comment by aymen-souid** [comment]
did you encounter this error when running extract_bert_features.sh ?  
![Screenshot from 2021-11-11 12-31-03](https://user-images.githubusercontent.com/92583830/141291131-b4056402-cba5-48ca-80b5-03449a56c351.png)

**Comment by juntaoy** [comment]
This is a tricky one, actually for BERT extraction you will need to set up another tf env that uses the 1.12 version of the TensorFlow.

**Comment by aymen-souid** [comment]
hello again!
I have run the code with colab, cause I have some problem with Cuda in my laptop, but running when running extract_bert_features.sh in collab it generates this error  and I can't  find such bert_config.json file 

Traceback (most recent call last):
  File "extract_features.py", line 339, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "extract_features.py", line 260, in main
    bert_config = modeling.BertConfig.from_json_file(FLAGS.bert_config_file)
  File "/content/aracoref/extract_bert_features/modeling.py", line 93, in from_json_file
    text = reader.read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./araBERT_01/tf_arabert01/bert_config.json; No such file or directory

**Comment by juntaoy** [comment]
it seems you didn't get the arabert uploaded to colab or didn't put it in the same location as you specified in extract_bert_features.sh

**Comment by aymen-souid** [comment]
in the pretrained files that you've provided i can't find any json file. I don't know how to keep processing, if you have a colab notebook , it would a pleasure if share it with me. 
this is my colab notebook if you can help: 
https://colab.research.google.com/drive/1OidCk7ZYYOO772AONmUjUcaNQFMuiHZ6#scrollTo=ON9wBGRVzt5l

**Comment by juntaoy** [comment]
You will need to download the tensorflow version of the arabert 0.1 (not sure if they still can be downloaded, I heard they switch to hugging face) and put them in the ./araBERT_01/tf_arabert01 folder.

**Comment by aymen-souid** [comment]
yes, unfortunately, they switch to hugging face

**Comment by aymen-souid** [comment]
hello again !
after running !python2 /content/aracoref/evaluate.py arabic_cleaned_bert
I got this error :

Running experiment: arabic_cleaned_bert
max_top_antecedents = 50
max_training_sentences = 50
top_span_ratio = 0.4
filter_widths = [
  3
  4
  5
]
filter_size = 50
char_embedding_size = 8
char_vocab_path = "/content/aracoref/bert-base-arabertv01/vocab.txt"
context_embeddings {
  path = "./content/aracoref/cc.ar.300.vec"
  size = 300
}
head_embeddings {
  path = "./content/aracoref/cc.ar.300.vec"
  size = 300
}
contextualization_size = 200
contextualization_layers = 3
ffnn_size = 150
ffnn_depth = 2
feature_size = 20
max_span_width = 30
use_metadata = true
use_features = true
model_heads = true
coref_depth = 2
lm_layers = 4
lm_size = 768
coarse_to_fine = true
max_gradient_norm = 5.0
lstm_dropout_rate = 0.4
lexical_dropout_rate = 0.5
dropout_rate = 0.2
optimizer = "adam"
learning_rate = 0.001
decay_rate = 0.999
decay_frequency = 100
train_path = "/content/aracoref/best-models/data/train.arabic.cleaned.pred.mentions.jsonlines"
eval_path = "/content/aracoref/best-models/data/dev.arabic.cleaned.pred.mentions.jsonlines"
conll_eval_path = "dev.arabic.v4_gold_conll"
lm_path = "bert_arb_conll12_cleaned_features.hdf5"
test_path = "/content/aracoref/best-models/data/test.arabic.cleaned.pred.mentions.jsonlines"
conll_test_path = "test.arabic.v4_gold_conll"
genres = [
  "bc"
  "bn"
  "mz"
  "nw"
  "pt"
  "tc"
  "wb"
]
eval_frequency = 500
report_frequency = 100
log_root = "logs"
max_step = 400000
use_joint_coref = true
use_e2e_annealing = false
log_dir = "logs/arabic_cleaned_bert"
Loading word embeddings from ./content/aracoref/cc.ar.300.vec...
Traceback (most recent call last):
  File "/content/aracoref/evaluate.py", line 17, in <module>
    model = cm.CorefModel(config)
  File "/content/aracoref/coref_model.py", line 24, in __init__
    self.context_embeddings = util.EmbeddingDictionary(config["context_embeddings"])
  File "/content/aracoref/util.py", line 174, in __init__
    self._embeddings = self.load_embedding_dict(self._path)
  File "/content/aracoref/util.py", line 191, in load_embedding_dict
    assert len(embedding) == self.size
AssertionError
